# please using absolute path for all path
data_path:     # absolute path of data path
output_path:  # absolute path of output path
iris_path:  # absolute path of IRIS path
register_mode: 'ORB'   # register mode. # Alternative option: "ORB"
mode: "com"          # whether to cut images when images is too large. com:NO large:YES

large_img_para:     # First cutting
  cut_size: 10000   # the size of cut img
  overlap: 100      # the overlap size of cut img

small_img_para:     # second
  cut_size: 2048    # the size of cut img
  overlap: 100    # the overlap size of cut img

core_num: 5   # the number of CPU core
cycle:    # cycle name
  - 1
  - 2
  - 3
  - 4
channel:
  0: DAPI.tif
  A: Cy5.tif
  T: Y7.tif
  C: TXR.tif
  G: Cy3.tif
barcode_path:     # gene-barcode file
search_region: 1.5    # the size of search region  in connect base on different cycle. # Alternative option: 2, 3, 4
temp_flag: 1    # whether to generate debug file. 0:NO 1:YES
blob_params:
  minThreshold: AUTO    # The threshold of pixel filtered. Alternative option: "AUTO", 0, 1, ..., 10.
  maxArea: 121   # The maximum area of point. Alternative option 65, 121, 145