# please using absolute path for all path
data_path:     # absolute path of data path
output_path:  # absolute path of output path
iris_path:  # absolute path of IRIS path
register_mode: 'ORB'   # register mode. # Alternative option: "ORB", "BRISK".
mode: "No" # whether to cut images when images is too large. all:large cuting and small cuting small:YES small cuting, No: No cuting

large_img_para:     # First cutting
  cut_size:    # the size of cut img
  overlap:       # the overlap size of cut img

small_img_para:     # Second cutting
  cut_size:     # the size of cut img
  overlap:     # the overlap size of cut img

core_num:    # the number of CPU core
cycle:    # cycle name
  - 1
  - 2
  - 3
  - 4
channel:
  0:
  A:
  T:
  C:
  G:
RNA_filter_flag: "No" # whether filtering the RNA
barcode_path:     # gene-barcode file
search_region:     # the size of search region  in connect base on different cycle. # Alternative option: 2, 3, 4
temp_flag:     # whether to generate debug file. 0:NO 1:YES
blob_params:
  minThreshold:     # The threshold of pixel filtered. Alternative option: "AUTO", 0, 1, ..., 10.
  maxArea:    # The maximum area of point. Alternative option 65, 121, 145